version: '3.8'
services:
  postgres:
    image: postgres:9.6
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'mydatabase'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: java_web_test_app
    environment:
      - DATABASE_URL=postgresql://roybha_user:6JbGz8Aksk5pIc0a6o4sPSpNi2VDq6bP@dpg-ctacd8pu0jms73ev0n3g-a/roybha
    ports:
      - "8080:8080"
volumes:
  postgres_data:
