version: '3.8'
services:
  app:
    build: .
    container_name: java_web_test_app
    environment:
      - DATABASE_URL=postgresql://roybha_user:6JbGz8Aksk5pIc0a6o4sPSpNi2VDq6bP@dpg-ctacd8pu0jms73ev0n3g-a/roybha
    ports:
      - "8080:8080"
volumes:
  postgres_data:
